name: Test

on: [pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirments-dev.txt

      - name: Run lint
        run: flake8 gentile --count --show-source --statistics

      - name: Test types
        run: mypy gentile --strict --non-interactive --pretty

      - name: Execute tests
        run: echo nothing yet
